# -*- coding: utf-8 -*-
"""source_code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUQ4pzq_2L9twimeC6egDwVomPa_pZRE

# NLP-Based Sentiment Analysis of IMDB Movie Reviews

This project uses Natural Language Processing (NLP) techniques
to classify IMDB movie reviews as positive or negative.
"""

import pandas as pd
import numpy as np

print("Libraries imported successfully")

import pandas as pd

# Load the dataset, specifying no header as the first row is data
df = pd.read_csv("IMDB Dataset.csv", header=None)

# Rename the relevant columns and drop the rest
# Based on inspection, column 0 is the review and column 1 is the sentiment
df = df[[0, 1]]
df.columns = ['review', 'sentiment']

# Drop the first row (index 0) as it appears to be a malformed entry
df = df.drop(index=0).reset_index(drop=True)

# Display first 5 rows with corrected column names
print("Corrected DataFrame head after dropping malformed row:")
print(df.head())

import pandas as pd

# Load the dataset, specifying no header as the first row is data
df = pd.read_csv("IMDB Dataset.csv", header=None)

# Rename the relevant columns and drop the rest
# Based on inspection, column 0 is the review and column 1 is the sentiment
df = df[[0, 1]]
df.columns = ['review', 'sentiment']

# Drop the first row (index 0) as it appears to be a malformed entry
df = df.drop(index=0).reset_index(drop=True)

# Display first 5 rows with corrected column names
print("Corrected DataFrame head after dropping malformed row:")
print(df.head())

# Count positive and negative reviews
print("Sentiment distribution:")
print(df["sentiment"].value_counts())

# Check for missing values
print(df.isnull().sum())

# Check number of rows and columns
print("Dataset shape:", df.shape)

# Check column names
print("Columns:", df.columns)

# Check first 5 rows
df.head()

# Count positive and negative reviews
print("Sentiment distribution:")
print(df["sentiment"].value_counts())

# Check for missing values
print(df.isnull().sum())

# Check for missing values
print(df.isnull().sum())

# Check duplicate rows
print("Number of duplicate rows:", df.duplicated().sum())

# Remove duplicate rows
df = df.drop_duplicates()

print("Dataset shape after removing duplicates:", df.shape)

# Display one positive review
print("Review:")
print(df[df["sentiment"] == "positive"]["review"].iloc[0])

print("\nSentiment:")
print(df[df["sentiment"] == "positive"]["sentiment"].iloc[0])

# Display one negative review
print("Review:")
print(df[df["sentiment"] == "negative"]["review"].iloc[0])

print("\nSentiment:")
print(df[df["sentiment"] == "negative"]["sentiment"].iloc[0])

positive = 1
negative = 0

# Convert sentiment into numbers
df["sentiment"] = df["sentiment"].map({
    "positive": 1,
    "negative": 0
})

# Display first 5 rows
df.head()

import re

# Function for cleaning reviews
def clean_text(text):
    text = text.lower()
    text = re.sub(r"<br />", " ", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

# Apply cleaning
df["clean_review"] = df["review"].apply(clean_text)

# Display original and cleaned review
print("Original Review:")
print(df["review"].iloc[0])

print("\nCleaned Review:")
print(df["clean_review"].iloc[0])

# Input data
X = df["clean_review"]

# Target data
y = df["sentiment"]

print("Input data:")
print(X.head())

print("\nTarget data:")
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training reviews:", len(X_train))
print("Testing reviews:", len(X_test))

from sklearn.feature_extraction.text import TfidfVectorizer

# Create TF-IDF vectorizer
tfidf = TfidfVectorizer(max_features=5000)

# Convert training reviews into numbers
X_train_tfidf = tfidf.fit_transform(X_train)

# Convert testing reviews into numbers
X_test_tfidf = tfidf.transform(X_test)

print("Training data shape:", X_train_tfidf.shape)
print("Testing data shape:", X_test_tfidf.shape)

from sklearn.linear_model import LogisticRegression

# Create the model
model = LogisticRegression(max_iter=1000)

# Filter out NaN values from y_train and corresponding rows from X_train_tfidf
nan_indices_train = y_train.isnull()
y_train_cleaned = y_train[~nan_indices_train]
X_train_tfidf_cleaned = X_train_tfidf[~nan_indices_train.values] # .values to align with sparse matrix indexing

# Convert y_train_cleaned to integer type, as LogisticRegression expects numerical labels
y_train_cleaned = y_train_cleaned.astype(int)

# Train the model
model.fit(X_train_tfidf_cleaned, y_train_cleaned)

print("Model training completed!")

# Predict sentiment for test reviews
y_pred = model.predict(X_test_tfidf)

print("Predictions completed!")
print(y_pred[:10])

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy percentage:", accuracy * 100, "%")

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred,
    target_names=["Negative", "Positive"]
))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

# Create confusion matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

# Display confusion matrix
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.colorbar()

plt.show()

# Test a new review
new_review = ["This movie was amazing and I really enjoyed it"]

# Clean the review
new_review_clean = [clean_text(new_review[0])]

# Convert to TF-IDF
new_review_tfidf = tfidf.transform(new_review_clean)

# Predict
prediction = model.predict(new_review_tfidf)

if prediction[0] == 1:
    print("Sentiment: Positive")
else:
    print("Sentiment: Negative")

import matplotlib.pyplot as plt

accuracy_percentage = accuracy * 100

plt.bar(["Logistic Regression"], [accuracy_percentage])

plt.title("Model Accuracy")
plt.ylabel("Accuracy (%)")
plt.ylim(0, 100)

plt.show()

# Convert numbers back to sentiment names

actual_sentiment = y_test.map({
    0: "Negative",
    1: "Positive"
})

predicted_sentiment = pd.Series(y_pred).map({
    0: "Negative",
    1: "Positive"
})

# Display first 10 predictions

results = pd.DataFrame({
    "Actual": actual_sentiment.values[:10],
    "Predicted": predicted_sentiment.values[:10]
})

results

# Test multiple new reviews

new_reviews = [
    "This movie was excellent and I really enjoyed it",
    "The movie was boring and a complete waste of time",
    "Amazing acting and wonderful story",
    "I hated this movie. It was terrible"
]

# Clean the reviews
cleaned_reviews = [clean_text(review) for review in new_reviews]

# Convert to TF-IDF
reviews_tfidf = tfidf.transform(cleaned_reviews)

# Predict
predictions = model.predict(reviews_tfidf)

# Display results
for review, prediction in zip(new_reviews, predictions):
    if prediction == 1:
        sentiment = "Positive"
    else:
        sentiment = "Negative"

    print("Review:", review)
    print("Predicted Sentiment:", sentiment)
    print("-" * 50)

# Count positive and negative reviews

sentiment_counts = df["sentiment"].value_counts()

# Create graph
plt.bar(
    ["Negative", "Positive"],
    [
        sentiment_counts.get(0, 0),
        sentiment_counts.get(1, 0)
    ]
)

plt.title("Distribution of Movie Review Sentiments")
plt.xlabel("Sentiment")
plt.ylabel("Number of Reviews")

plt.show()

# Save the cleaned dataset

df.to_csv("IMDB_Cleaned_Dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

test_review = input("Enter a movie review: ")

# Clean the review
cleaned_test_review = clean_text(test_review)

# Convert to TF-IDF
test_review_tfidf = tfidf.transform([cleaned_test_review])

# Predict
prediction = model.predict(test_review_tfidf)

if prediction[0] == 1:
    print("Predicted Sentiment: Positive")
else:
    print("Predicted Sentiment: Negative")